.\" Manpage for 108monstre.
.\" Contact poulet_a@epitech.eu and broggi_t@epitech.eu in to correct errors or typos.
.TH 108MONSTER "10" "Mars 2014" "1.0" "108monstre man page"
.SH NAME
.PP
108monstre \- evaluate polynomials and print rationals functions

.SH SYNOPSIS
.PP
\fB./108monstre\fR [\fPPARAMS\fR]...
.SH DESCRIPTION
.PP

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Display this help and exit
.TP

.SH INTERACTIVE MODE
.PP
The availables options in interactive mode are the following :
.TP

.SH EXAMPLES
.TP

.TP
\fB./108monstre\fR
Run the interactive mode ;)

.SH SEE ALSO
No related manpage.

.SH REPORTING BUGS
No known bugs.
.br
Report ./108monstre bugs to arthur.poulet@epitech.eu and thibaut.broggi@epitech.eu

.SH AUTHOR
poulet_a, broggi_t
